easy_admin:
  design:
    assets:
      css:
        - '/assets/bs-tags/bootstrap-tagsinput.css'
      js:
        - '/assets/bs-tags/bootstrap-tagsinput.js'
    menu:
      - {label: "Entities"}
      - label: "Posts"
        children:
          - {entity: Post, label: "Posts list", icon: "th-list"}
          - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}, permission: 'ROLE_ADMIN'}
      - label: "Category"
        children:
          - {entity: Category, label: "List all categories", icon: "th-list"}
          - {entity: Category, label: "Add category", icon: "plus"}
      - Tag
      - {label: "Settings"}
      - {entity: User, icon: "user", permission: 'ROLE_ADMIN'}
  site_name: 'OverSeas <b>Media</b>'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
  entities:
    Post:
      class: App\Entity\Post
      label: "Post"
      form:
        fields:
            - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
            - title
            - {property: 'content'}
            - createdAt
            - published
            - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
            - category
            - { property: 'tags', type: 'App\Form\TagType', type_options: {attr: {data-role: 'tagsinput'}}}
            - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-5'}
            - { property: 'thumbnailFile', type: 'vich_image' }
            - { property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\AttachmentType', by_reference: false} }
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Some posts from the other world"
        fields: ['title', 'content', 'createdAt', {property: 'user.email', label: 'Author', permission: 'ROLE_ADMIN'}, {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]
        filters: ['published']
      show:
        fields:
          - title
          - {property: 'content', type: 'raw'}
          - createdAt
          - published
          - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}
          - {property: 'attachments', template: 'images.html.twig' }
          - tags
      edit:
        help: "Hello there"
      new:
        item_permission: 'ROLE_ADMIN'

    Category:
      class: App\Entity\Category
    Tag:
      class: App\Entity\Tag
      form:
        fields:
          - name
          - slug
    User:
      class: App\Entity\User
      list:
        item_permission: 'ROLE_ADMIN'