vich_uploader:
    db_driver: orm

    mappings:
        post_thumbnails:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'

        post_attachments:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
